import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import MainHeader from "./components/MainHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen relative w-full antialiased`}
      >
        <div className="absolute w-full text-center z-10000">
          <Header />
        </div>

        {/* <div className="w-full flex items-center justify-center  fixed bottom-14 z-[100]">
          <div className="w-screen ">
            <MainHeader />
          </div>
        </div> */}
        {children}
      </body>
    </html>
  );
}
